system:
    address: 0.0.0.0
    port: "5244"
    tls: false
    cert_file: ""
    key_file: ""
    prefix: ""
    search: false
    download: false
    static: ""
    site_url: ""
    password: ""
    file_download_timeout: 86400
site:
    title: 文件管理系统
    logo: "https://devui.design/components/assets/logo.svg"
    footer_text: "iRorikon"
    footer_link: "https://github.com/iRorikon"
    script: ""
    sort: size-ascend
jwt:
    expire: 720000
storage:
    type: local
    show_hidden: false
    path: ./
zap:
    level: debug
    prefix: '[HTTP-FILE]'
    format: json
    director: logs
    encode_level: LowercaseLevelEncoder
    stacktrace_key: stacktrace
    max_age: 3600
    show_line: true
    log_to_console: true
cors:
    mode: allow-all
    whitelist: []
