system:
    address: 0.0.0.0
    port: "5244"
    tls: false
    cert_file: ""
    key_file: ""
    prefix: ""
    search: false
    download: false
    static: ""
    site_url: ""
    password: ""
    file_download_timeout: 86400
site:
    title: 文件管理系统
    version: "1.0.0"
    # logo: "https://img.oez.cc/2020/12/19/0f8b57866bdb5.gif"
    logo: "https://devui.design/components/assets/logo.svg"
    footer_text: "iRorikon"
    footer_link: "https://github.com/iRorikon"
    music_img: https://img.oez.cc/2020/12/19/0f8b57866bdb5.gif
    script: ""
    autoplay: true
    sort: size-ascend
    preview:
        text:
            - txt
            - htm
            - html
            - xml
            - java
            - properties
            - sql
            - js
            - md
            - json
            - conf
            - ini
            - vue
            - php
            - py
            - bat
            - gitignore
            - yml
            - go
            - sh
            - c
            - cpp
            - h
            - hpp
jwt:
    expire: 0
storage:
    type: local
    show_hidden: false
    path: "C:/Users/irori/Downloads/"
zap:
    level: debug
    prefix: '[HTTP-FILE]'
    format: json
    director: logs
    encode_level: LowercaseLevelEncoder
    stacktrace_key: stacktrace
    max_age: 3600
    show_line: true
    log_to_console: true
cors:
    mode: allow-all
    whitelist: []
